// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/date/{date}": {
            "get": {
                "description": "Get rates by date",
                "produces": [
                    "application/json"
                ],
                "summary": "Get rates by date",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2023-06-17",
                        "description": "Date of rate",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GetRatesByDateResponse"
                        }
                    }
                }
            }
        },
        "/api/exchange/{from}/{to}/{value}": {
            "get": {
                "description": "ExchangeRate",
                "produces": [
                    "application/json"
                ],
                "summary": "ExchangeRate",
                "parameters": [
                    {
                        "type": "string",
                        "default": "USD",
                        "description": "From currency",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "RUB",
                        "description": "To currency",
                        "name": "to",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "number",
                        "default": 100,
                        "description": "Value",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ExchangeRateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ExchangeRateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "result": {
                            "type": "number",
                            "example": 10.91
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "controllers.GetRatesByDateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "rates": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RateSwagger"
                            }
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.RateSwagger": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rates API",
	Description:      "api for getting rates, exchange rates",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
